### ISSUE TITLE
Add support for null_flavour at the ELEMENT level

### ISSUE THREAD

**Issue by ppazos** [ehrbase/openEHR_SDK#131]
## Background ##

In the FHIR bridge we could have missing data, or even data that is semantically similar to the openEHR ELEMENT.null_flavour, but currently the code generated doesn't allow to record the null_flavour.

## Acceptance criteria ##

At the same level the fields for ELEMENT.value are generated, we need to generate field for the ELEMENT.null_flavour which is a DV_CODED_TEXT.

## Success criteria ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by stefanspiska** [comment]
Fixed in https://github.com/ehrbase/openEHR_SDK/pull/153 which will become release 1.0.0
see 
https://github.com/ehrbase/openEHR_SDK/blob/release/v1.0.0/CHANGELOG.md for changes
https://github.com/ehrbase/openEHR_SDK/blob/release/v1.0.0/UPDATING.md for how to update
