### ISSUE TITLE
Duplicate generation

### ISSUE THREAD

**Issue by BirgitSaalfeld** [ehrbase/openEHR_SDK#139]
## Steps to reproduce ## 
During the mapping in the branch in IntelliJ: 
Branch: https://github.com/ehrbase/fhir-bridge/compare/develop...feature/num71_travelmapping2

## Actual result ##

The generator creates additional "BundeslandRegionDefiningCode", but it is already existing in the shared definition
![Screenshot from 2020-11-16 11-05-49](https://user-images.githubusercontent.com/70131678/99240605-04764100-27fd-11eb-8b7d-a9bd1e8c6ef4.png)

## Expected result ##

No additional region defining code

## Success criteria ##

- [ ] Generator creates only necessary classes

**Comment by stefanspiska** [comment]
The BundeslandRegionDefiningCode in shared definition must be an artifact from an old version.
The one in not in   shared definition is correct. 
The sdk right now dos not support generation  of sheered enum if not part of the openEhr standard.

**Comment by BirgitSaalfeld** [comment]
Ok, I use the new generated files. 

@stefanspiska  Shall I delete those in the shared definition? Or do you delete?

**Comment by stefanspiska** [comment]
Please delete ist. if not used anywhere. 
If it is used anywhere you my want to recreate the classes.

**Comment by BirgitSaalfeld** [comment]
Deleted 
- ReiseDefiningCode
- BundeslandRegionDefiningCode
- LandDefiningCode
from shareddefinition.java
