### ISSUE TITLE
SnomedCode 261665006 missing in generator

### ISSUE THREAD

**Issue by BirgitSaalfeld** [ehrbase/openEHR_SDK#140]
## Steps to reproduce ## 

When using the generator 3.0.7 for "Reiseaktivitaet.opt" there is a snomed-code missing
**Resources**
- generator 3.0.7
https://ckm.highmed.org/ckm/templates/1246.169.1152
```
java -jar ../openEHR_SDK/generator/target/generator-0.3.7.jar -opt src/main/resources/opt/Reiseaktivitaet.opt -out src/main/java/ -package org.ehrbase.fhirbridge.opt
```

## Actual result ##

```
[main] INFO org.ehrbase.terminology.client.terminology.TerminologyProvider - Unknown  value 261665006 in Terminology SNOMED Clinical Terms
```
- value is for `unknown`

## Expected result ##

no error message when using the generator

## Success criteria ##

- [ ] no error message when using the generator

**Comment by stefanspiska** [comment]
@BirgitSaalfeld 
You can ignore this INFO
