### ISSUE TITLE
NullPointer thrown Flattener.flatten

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/openEHR_SDK#168]
## Configuration information
    "ehrbase_version": "0.14.0",
    "openehr_sdk_version": "9dc1adb",
    "archie_version": "dc09642",
    "jvm_version": "Oracle Corporation 11.0.9.1+1",
    "os_version": "Linux amd64 5.10.2-2-MANJARO",
    "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"

## Steps to reproduce ## 
Setup Fhir-Bridge [branch](https://github.com/ehrbase/fhir-bridge/tree/feature/NUM_73_mapping_questionnaire) and run this [test](https://github.com/ehrbase/fhir-bridge/blob/2837a858e741373b4a45c4799ed77057fe9ae9e6/src/test/java/org/ehrbase/fhirbridge/fhir/QuestionnaireResponseIT.java#L65). 

## Actual result ##
Try to use Flattener .flatten on a Composition. Null Pointer is returned and i cannot distinct from what (maybe its my own fault).
The debuger shows that the Template provider managed to load the opt.

## Expected result (Acceptance Criteria) ##
Correct output of an D4LQuestionnaireComposition Object.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
javers-core intruduces an old classgraph dependency you need to add


```
      <dependency>
                <groupId>io.github.classgraph</groupId>
                <artifactId>classgraph</artifactId>
                <version>4.8.97</version>
            </dependency>
```

to the dependency management.
