### ISSUE TITLE
Terminologies get converted to generic types

### ISSUE THREAD

**Issue by jsachau** [ehrbase/openEHR_SDK#171]
I'm currently working on the diagnosis mapping for the fhir-bridge project. We noticed a problem when generating the composition classes with the generator.jar. In the opt file certain attributes have terminologies (either ICD or SNOMED codes) which are not converted correctly into the Java class structure. They are either converted to `DvCodedText` or `String`. The expected behavior is that an Enum is created which contains the codes. Because of the error I can not commit the opt file but I will paste it in this issue for you to test. The attributes are the following:

```
/data[at0001]/items[at0003 and name/value='Problem/Diagnose']/value|value
/data[at0001]/items[at0002 and name/value='Unbekannte Diagnose']/value|value
/data[at0001]/items[at0002 and name/value='Name des Problems']/value
```

The fields are contained in the `VorliegendesDiagnoseEvaluation`, `AusgeschlosseneDiagnoseEvaluation`, `UnbekannteDiagnoseEvaluation` classes. @wulffant modified the opt so that a `DvCodedText` is generated in  `VorliegendesDiagnoseEvaluation` and `String` are generated in the other two classes.

Here is the opt file for testing
[GECCO_Diagnose.opt.zip](https://github.com/ehrbase/openEHR_SDK/files/5867856/GECCO_Diagnose.opt.zip)

**Comment by SevKohler** [comment]
The newest version of the GECCO_Diagnose works as it should when generating Code.
