### ISSUE TITLE
AqlToDtoParser fails to parse a query that runs fine against ehrbase server

### ISSUE THREAD

**Issue by jhahkala** [ehrbase/openEHR_SDK#176]
## Configuration information

- EHRbase version: ehrbaseorg/ehrbase:latest docker image (says 0.14.0 at startup)
- openEHR_SDK version: developer-SNAPSHOT (commit gc816cfc7)
- Archie version:?
- PostgreSQL version:ehrbaseorg/ehrbase-postgres:latest
- Java Runtime version:11.0.9.1
- Operating System version:ubuntu 20.10 

## Steps to reproduce ## 
Trying to parse and aql with (AqlDto dto = new AqlToDtoParser().parse(aql))) where the aql is "SELECT o FROM EHR e CONTAINS OBSERVATION o" gives:
org.ehrbase.aql.parser.AqlParseException: No value present
	at org.ehrbase.aql.parser.AqlToDtoParser.parse(AqlToDtoParser.java:42) ~[aql-develop-v0.3.7-339-gc816cfc7-1.jar:na]

But running it against ehrbase aql endpoint works fine

## Actual result ##

org.ehrbase.aql.parser.AqlParseException: No value present
	at org.ehrbase.aql.parser.AqlToDtoParser.parse(AqlToDtoParser.java:42) ~[aql-develop-v0.3.7-339-gc816cfc7-1.jar:na]

## Expected result (Acceptance Criteria) ##

parsed query

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by danielatomoiaga** [comment]
The query below has the same issue, can be ran against the ehr server but the aql parser will throw an exception:

`Select e/ehr_id/value as F1, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value as F2, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value as F3 from EHR e contains (COMPOSITION c0 and SECTION s4[openEHR-EHR-SECTION.adhoc.v1] contains OBSERVATION o[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]) where (e/ehr_id/value matches {'47dc21a2-7076-4a57-89dc-bd83729ed52f'} and c0/archetype_details/template_id/value matches {'Corona_Anamnese'})`

**Comment by jhahkala** [comment]
I guess it's related to contains observation as that seems to be the only common thing in the two queries that is not used in almost all queries.
