### ISSUE TITLE
What is the meaning of the pipe in the @Path annotations?

### ISSUE THREAD

**Issue by ppazos** [ehrbase/openEHR_SDK#19]
E.g. @Path("/context/end_time|value")

Because the openEHR path to the value would be /context/end_time/value (without the pipe)

**Comment by stefanspiska** [comment]
This is inspiriert from https://github.com/ethercis/ethercis/blob/master/doc/flat%20json.md
`/` represent Archetyp steps in the path 
'|' represent RM Model steps in the path
