### ISSUE TITLE
Classes under shareddefinition in the generated code are common to all generated code, why not add them statically in the client library as other classes like annotations?

### ISSUE THREAD

**Issue by ppazos** [ehrbase/openEHR_SDK#20]
There are some classes/interfaces mentioned in the generated code that are defined in the client library, but in the generated code there are also common classes under "shareddefinition", which will be generated for each OPT. Why not adding those to the library itself?

**Comment by stefanspiska** [comment]
The  common classes under "shareddefinition" are generated from global Terminologies. Right now this are only the openehr one but if we build in support for a Terminology server this could also generated from a snomed Valusets for example.  Thus the content in shareddefinition depends on the Templates.

**Comment by ppazos** [comment]
For current values (territory, category, etc.) those will always be under the "openehr" terminology, this is specified in the standard. At least those will not depend on any other terminology in the future, so do not really depend on the OPT, is that way by spec.
