### ISSUE TITLE
Future Client Libraries

### ISSUE THREAD

**Issue by foodplanet** [ehrbase/openEHR_SDK#24]
Hello, are there client libraries planned or in progress for other languages like Python or JavaScript?

**Comment by Geisterfalle** [comment]
Hi @foodplanet, unfortunately, this is not planned, yet.

**Comment by foodplanet** [comment]
Okay thanks, but is a comprehensive documentation in progress? As a Java and ehrbase beginner I find it a bit difficult to use the client library. The few examples on https://ehrbase.readthedocs.io/en/latest/ leave many questions open.

**Comment by stefanspiska** [comment]
The library is currently in alpha  so expect a more complete documentation when we are in the beta.  Right now it is best to look into the Integration tests.

**Comment by jakesmolka** [comment]
Hey @foodplanet! If you are still interested in learning more about the SDK please check out our recent addition to the documentation: https://ehrbase.readthedocs.io/en/latest/04_sdk/index.html
