### ISSUE TITLE
Generated classes are lacking "name" attribute

### ISSUE THREAD

**Issue by jakesmolka** [ehrbase/openEHR_SDK#26]
My current experiment with a template generates classes with all the necessary and correct attributes like

```
(...)
@Path("/data[at0001]/items[at0073]/value")
@Choice
private ProblemDiagnoseAttributDiagnostischeSicherheitChoice diagnostischeSicherheit;
(...)
```

**except** the `name`, which is necessary by RM. So this snippet would need manual adding of the `name` like

```
(...)
@Path("/data[at0001]/items[at0073]/value")
@Choice
private ProblemDiagnoseAttributDiagnostischeSicherheitChoice diagnostischeSicherheit;
(...)

@Path("/name")
private DvText name;

public DvText getName() {
    return name;
}

public void setName(DvText name) { 
   this.name = name;
}
```

I'd guess this needs to be added as a custom generation handling or rule, so a `name` is always created for all `LOCATABLE` type classes and sub-classes.

**Comment by Geisterfalle** [comment]
This was resolved by https://github.com/ehrbase/openEHR_SDK/pull/41. Please re-open if this is not the case.
