### ISSUE TITLE
Problem with some cardinality validations define in template

### ISSUE THREAD

**Issue by subigre** [ehrbase/openEHR_SDK#282]
## Configuration information

```json
{
  "ehrbase_version": "0.17.2",
  "openehr_sdk_version": "321ef09",
  "archie_version": "1.0.3",
  "jvm_version": "AdoptOpenJDK 11.0.11+9",
  "os_version": "Windows 10 amd64 10.0",
  "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}
```

## Steps to reproduce ## 

Based on errors reported in https://github.com/ehrbase/ehrbase/pull/654, I tried to reproduce the problem with the a simple test case.

Create a composition using the following template and composition:

- [test_section_occurence.v0.opt.txt](https://github.com/ehrbase/openEHR_SDK/files/7515521/test_section_occurence.v0.opt.txt)
- [test_section_occurence.v0.json.txt](https://github.com/ehrbase/openEHR_SDK/files/7515523/test_section_occurence.v0.json.txt)

PS: I also tried with a real template ([International Patient Summary.opt.txt](https://github.com/ehrbase/openEHR_SDK/files/7515585/International.Patient.Summary.opt.txt)) and I am able to create a commit a composition without the mandatory sections.

## Actual result #

`201 Created`

## Expected result (Acceptance Criteria) ##

`422 Unprocessable Entity` as the composition does not comply with cardinality defines in the template.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by wlad** [comment]
is also covered by a robot test

```
# robot command to execute related test case(s)

robot -d results -i 282 robot/COMPOSITION_TESTS
```

**Comment by subigre** [comment]
Fixed by https://github.com/ehrbase/openEHR_SDK/pull/309
