### ISSUE TITLE
OPTParser not parsing cagegory.code and category.value 

### ISSUE THREAD

**Issue by flowrider3000** [ehrbase/openEHR_SDK#328]
## Configuration information

- EHRbase version: 0.20.0-SNAPSHOT
- openEHR_SDK version: v1.17.0
- Archie version: 1.0.4
- PostgreSQL version: 13.4-alpine
- Java Runtime version: 
```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```
- Operating System version: macOS 12.2.1 (21D62)

## Steps to reproduce ## 

```
final WebTemplate webTemplate = new OPTParser(templateProvider.find("single text test template").get()).parse();
final WebTemplateNode category = webTemplate.getTree().findChildById("category").get();
```

Template see [single text test template.opt.zip](https://github.com/ehrbase/openEHR_SDK/files/8132536/single.text.test.template.opt.zip)

## Actual result ##

Category terminology id and category code are not parsed from the template.

## Expected result (Acceptance Criteria) ##

Category terminology id and category code should be parsed from the template (values "openehr"; 433). 

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
This is do to 
https://discourse.openehr.org/t/composition-archetypes-are-generated-with-atcode-in-eventcontext/3202

so you template is wrong
