### ISSUE TITLE
AQL endpoint null value returned leads to NullPointerException

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/openEHR_SDK#371]
## Configuration information
Fhir bridge + better platform 
Aql endpoint cannot parse null object from better

- EHRbase version: Ehrscape
- openEHR_SDK version: 1.19
- Archie version: -
- PostgreSQL version: -
- Java Runtime version: 18
- Operating System version: -

## Steps to reproduce ## 
```Java
  Identifier pseudonym = getIdentifier();
        Query<Record1<UUID>> query = Query.buildNativeQuery(
                "SELECT e/ehr_id/value from EHR e WHERE e/ehr_status/subject/external_ref/id/value = '" + pseudonym.getValue() + "'", UUID.class);
   openEhrClient.aqlEndpoint().execute(query);
```
## Actual result ##
```Java
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonArray()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestAqlEndpoint.execute(DefaultRestAqlEndpoint.java:106) ~[client-1.19.0.jar:na]
	at org.ehrbase.fhirbridge.openehr.camel.EhrLookupProcessor.createOrGetPatientEhr(EhrLookupProcessor.java:131) ~[classes/:na]
```
openEHR SDK cant handle null return values provided by the better platforms aql endpoint

## Expected result (Acceptance Criteria) ##
Empty list.

## Definition of Done ##
Empty list returned instead of null pointer

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by SevKohler** [comment]
I tried a query which returns non empty reults which worked. In combination with ehrbase the query works.

**Comment by vidi42** [comment]
Ideally we should also switch from Gson to Jackson

**Comment by dmitrytulba** [comment]
@SevKohler please provide
1.  EHRbase version that  was used 
https://github.com/ehrbase/ehrbase/tags

2.  Exact value 'pseudonym.getValue()' returns
`"SELECT e/ehr_id/value from EHR e WHERE e/ehr_status/subject/external_ref/id/value = '" + pseudonym.getValue() + "'"`

**Comment by SevKohler** [comment]
Was on next to that time. Just check the current version of june.
