### ISSUE TITLE
Arrtifact id in jitpack aql and not openEHR SDK

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/openEHR_SDK#374]
<dependency>
	    <groupId>com.github.ehrbase.openEHR_SDK</groupId>
	    <artifactId>aql</artifactId>
	    <version>v1.19.0</version>
	</dependency>
	
As a result, the import does not work, at least for me. 

`Could not find artifact com.github.ehrbase.openEHR_SDK:aql:pom:v1.19.0 in jitpack.io (https://jitpack.io)`
Mvn version:
```Bash
Maven home: /opt/maven
Java version: 18.0.1.1, vendor: N/A, runtime: /usr/lib/jvm/java-18-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.13-1-manjaro", arch: "amd64", family: "unix"
```
My old import works:
```XML
         <ehrbase-sdk.version>10cce9b</ehrbase-sdk.version>
....
       <dependency>
            <groupId>com.github.ehrbase</groupId>
            <artifactId>openEHR_SDK</artifactId>
            <version>${ehrbase-sdk.version}</version>
        </dependency>
```

**Comment by vidi42** [comment]
Hi @SevKohler . After version 1.5.0 the groupid of the openEHR_SDK was changed to `org.ehrbase.openehr.sdk` (previously `com.github.ehrbase.openEHR_SDK`)

Can you try with the new groupId?

**Comment by SevKohler** [comment]
`The POM for org.ehrbase.openehr.sdk:aql:jar:v1.19.0 is missing, no dependency information available`
For artificat id aql, now im trying sdk

**Comment by stefanspiska** [comment]
@SevKohler 
https://mvnrepository.com/artifact/org.ehrbase.openehr.sdk/aql/1.19.0

**Comment by SevKohler** [comment]
@stefanspiska always a pleasure, thanks

**Comment by vidi42** [comment]
> @SevKohler https://mvnrepository.com/artifact/org.ehrbase.openehr.sdk/aql/1.19.0

@SevKohler if this works for you please close the issue once you have a resolution
