### ISSUE TITLE
Update ANTLR4 to version 4.10.*

### ISSUE THREAD

**Issue by flowrider3000** [ehrbase/openEHR_SDK#375]
## Background ##

ANTLR4 should be updated to 4.10.* version because of breaking changes (Generated 4.10 lexers and parsers are incompatible with code generated by previous versions of ANTLR). 
Without the update, applications using the openEHR_SDK library can not use latest ANTLR4 features.

See https://github.com/antlr/antlr4/releases for the full changelog.

## Acceptance Criteria ##

- [ ] ANTLR4 is updated to the latest version (currently 4.10.1)

## Definition of Done ##

- [ ] Output has been reviewed or presented and has been approved
- [ ] Documentation has been updated (Sphinx, Javadoc, Guidelines, etc.) if applicable

**Comment by stefanspiska** [comment]
blocked by https://github.com/openEHR/archie/pull/430
@vidi42

**Comment by flowrider3000** [comment]
Fixed in #428 . Thx!
