### ISSUE TITLE
AqlToDtoParser ignores some part of the query as converting the AQL to Dto

### ISSUE THREAD

**Issue by smnrdln** [ehrbase/openEHR_SDK#380]
## Configuration information

- EHRbase version:
- openEHR_SDK version: v1.5.0 (Same behaviour with v1.19.0)
- Archie version:
- PostgreSQL version:
- Java Runtime version:
- Operating System version:

## Steps to reproduce ## 
During testing the app [num-portal](https://github.com/NUM-Forschungsdatenplattform/num-portal) we noticed that the AQL query process doesn't work correctly. As mentioned and discussed [here](https://github.com/NUM-Forschungsdatenplattform/num-portal-webapp/issues/348) some part of the AQL query will be ignored after parsing and converting to Dto. For example, given the following AQL query:

```
SELECT
  e1/data[at0001]/items[at0002]/value/defining_code/code_string as code
FROM
  EHR e
  contains COMPOSITION c0[openEHR-EHR-COMPOSITION.report.v1]
  contains EVALUATION e1[openEHR-EHR-EVALUATION.problem_diagnosis.v1]
WHERE
  (c0/archetype_details/template_id/value = 'KDS_Diagnose'
  AND e1/data[at0001]/items[at0002]/value/defining_code/code_string LIKE 'I50*')
```
gives the following result:

```
SELECT
  c0 as KDS_Diagnose
FROM
  EHR e
  contains COMPOSITION c0[openEHR-EHR-COMPOSITION.report.v1]
WHERE
  c0/archetype_details/template_id/value = 'KDS_Diagnose'
```

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
@smnrdln 

'like ' is currently not supported by the sdk aql dto model.

(@vladislavploaia @vidi42  for info)

**Comment by Unaimend** [comment]
Is there any way to workaround this issue?

**Comment by stefanspiska** [comment]
this was fixed in the new AQL Dto model https://github.com/ehrbase/openEHR_SDK/pull/464
