### ISSUE TITLE
Client support for managing compositions trough contributions

### ISSUE THREAD

**Issue by vidi42** [ehrbase/openEHR_SDK#398]
## Background ##

The only way to manage compositions through contributions in EHRbase is by directly calling the REST API.
Add support to the client for creating, and reading contributions. As well as wrapping operations on composition inside a contribution.

## Acceptance criteria ##

- [ ] New contribution endpoint added to the [client](https://github.com/ehrbase/openEHR_SDK/tree/develop/client/src/main/java/org/ehrbase/client/openehrclient)
- [ ] Support for creating and get contribution endpoints
- [ ] Helper class to wrap composition create/update/delete inside a contribution
- [ ] Robot tests for composition create/update/delete through contributions

## Definition of Done ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by vidi42** [comment]
@OndrejMarcncak Yes, you submit a PR for it.

**Comment by OndrejMarcncak** [comment]
Hi, i am still working on it, but i have a lot of work at school. Can i still work on this?

**Comment by vidi42** [comment]
Hey, @OndrejMarcncak thank you for the update. Sure, however, we'll let you know if this gets a higher priority.
If you already have something in there that you can share with us, it would help us if you could open a draft PR so we can get an early look.

**Comment by OndrejMarcncak** [comment]
Hi, I have started to work on this issue today, but i am having trouble with building the project. Error is:
```
Unrecognized option: --add-exports
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
I would like to know, what Java is recomended, I am using JDK 1.8 right now.

**Comment by OndrejMarcncak** [comment]
Hi, I have started to work on this today, but I am having this problem:
```
Unrecognized option: --add-exports
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
I am using Java 11 with mvn 3.8.6.

**Comment by vidi42** [comment]
> Hi, I have started to work on this today, but I am having this problem:
> 
> ```
> Unrecognized option: --add-exports
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> ```
> 
> I am using Java 11 with mvn 3.8.6.

@OndrejMarcncak which branch did you use and what command did you run when you got this?

**Comment by OndrejMarcncak** [comment]
It is OK now, I used java 17 and it is working, I was using brach develop and running command mvn clean install. But I will need more info about this problem. waht exactly is my job? I am not familiar with terminology in EHR systems and I would like to know more about Contribution and Compositions. Maybe som hepl like class diagram would hepl me if you have time.

**Comment by OndrejMarcncak** [comment]
My other question is if it is possible to solve this issue without having server and DB.

**Comment by vidi42** [comment]
> It is OK now, I used java 17 and it is working, I was using brach develop and running command mvn clean install. But I will need more info about this problem. waht exactly is my job? I am not familiar with terminology in EHR systems and I would like to know more about Contribution and Compositions. Maybe som hepl like class diagram would hepl me if you have time.

@OndrejMarcncak as described in the Acceptance Criteria part, we need REST API Client enhancements to support creating and retrieving contributions. Plus some wrappers for which transform composition CRUD operations into contributions


> My other question is if it is possible to solve this issue without having server and DB.
@OndrejMarcncak Theoretically yes, but I would suggest using a DB to test this from one end to another.

**Comment by stefanspiska** [comment]
closed by https://github.com/ehrbase/openEHR_SDK/pull/406
