### ISSUE TITLE
SdkException should not extend RuntimeException

### ISSUE THREAD

**Issue by flowrider3000** [ehrbase/openEHR_SDK#458]
### Background

Unchecked exceptions can cause unexpected behaviour and make it difficult for developers to understand what went wrong. Checked exceptions, provide clear information about potential issues and allow developers to handle those issues appropriately.

Every library interface should provide checked exceptions. Therefore, the openEHR_SDK should not throw unchecked exceptions and should make the error handling more implicit. By modifying the library to use checked exceptions, the overall  usability and reliability of the library can be improved. Developers who use the library will be better equipped to handle potential issues and will have a clearer understanding of how the library should be used.

### Enhancement

I would propose the following changes:
- `SdkException` should extend `Exception` instead of `RuntimeException` (see https://github.com/ehrbase/openEHR_SDK/blob/develop/util/src/main/java/org/ehrbase/util/exception/SdkException.java#L20)
- Every public method of the openEHR_SDK should have `throws SdkException` in the method signature
- Only `SdkExceptions` are allowed to be thrown by the sdk methods. Other exceptions like `JsonProcessingException` (see https://github.com/ehrbase/openEHR_SDK/blob/develop/client/src/main/java/org/ehrbase/client/openehrclient/ContributionEndpoint.java#L39) and `IOException` (see https://github.com/ehrbase/openEHR_SDK/blob/develop/client/src/main/java/org/ehrbase/client/openehrclient/ContributionEndpoint.java#L48) are not allowed and must be wrapped in a `SdkException`

### Further information

Would love to get your feedback on this topic. If the change request is ok for you, I would like to spend some time on the implementation after my holidays. 

You know where to find me ;-)

**Comment by vmueller-vg** [comment]
Just my opinion on that:

it depends on what went wrong. if for example i am running a validation i would appreciate a checked exception. But if something goes wrong in an unexpected or unrecoverable way that does not make sense. If we want a common super class for checked exceptions in the SDK we can talk about introducing one, but that would be new and then we would have to talk about where it makes sense. Having a common super class for RuntimeExceptions thrown by the SDK makes sense none the less so maybe the current SdkException should be renamed to SdkRuntimeException

**Comment by vmueller-vg** [comment]
We discussed this internally and pretty much agree on this:

it depends on what went wrong. if for example i am running a validation i would appreciate a checked exception. But if something goes wrong in an unexpected or unrecoverable way that does not make sense. In general exception should only be declared (and be of the checked variety) if you expect the caller to do something with it. 
Having every method in the API throw a checked exception is a huge breaking change for everyone who is using the SDK and would also introduce a stupendous amount of catching exceptions that can not occur, might have no meaning or are just things you would rethrow as RuntimeException. Also Wrapping every Exception in a checked exception would require overly complicated exception handling based on caused-by-chains.

If we want a common super class for checked exceptions in the SDK we can talk about introducing one, but that would be new and then we would have to talk about where it makes sense. If we want to keep a common super class for RuntimeExceptions thrown by the SDK maybe the current SdkException should be renamed to SdkRuntimeException. 

Lastly it goes to say that we are fully aware that the exception handling and throwing in the SDK (and also ehrbase) needs to be reworked/adjusted and documented in many places. And this will be taken care of step by step.
