### ISSUE TITLE
Update Archie version to v3.6.0, at least

### ISSUE THREAD

**Issue by josepedrocorreia** [ehrbase/openEHR_SDK#542]
### Background

Archie is, at the time of writing, at version v3.6.0 (see [here](https://github.com/openEHR/archie/releases)). This version includes functionality that I would like to use via the SDK.

### Task specification

Update dependencies to Archie to v3.6.0 (at least, a newer version would also be fine) and verify if everything still works as expected.

**Comment by vmueller-vg** [comment]
archie version is >=  v3.11.0 for SDK version >= 2.19.0
