### ISSUE TITLE
Writing a composition in a language other than English

### ISSUE THREAD

**Issue by hkabbech** [ehrbase/openEHR_SDK#603]
I am trying to write a composition with Dutch variables instead of English.

**These are the steps I've been taken:**
1. Wrote and downloaded an OPT template in both English and Dutch.
2. Generated the java composition class based on the template using the SDK generator
3. Built the transform class and precised the Dutch language `composition.setLanguage(Language.NL);`
    Also precised the Dutch language of the used archetype `alcoholConsumptionSummaryEvaluation.setLanguage(Language.NL);`
5. Generated a composition using the REST transform API

The output is a Composition with variable names in English instead of required Dutch (see overview of a generated composition below)
I've also write an AQL query to retrieve a variable name by calling a specific node but the name shown was also in English.

Am I missing a step during the generation of java class, while definition the composition steps or transforming the data?

Thank you for your help!

```
{
    "_type": "COMPOSITION",
    "name": {
        "_type": "DV_TEXT",
        "value": "alcohol_gebruik"
    },
    "archetype_details": {
        "archetype_id": {
            "value": "openEHR-EHR-COMPOSITION.encounter.v1"
        },
        "template_id": {
            "value": "alcohol_gebruik"
        },
        "rm_version": "1.0.4"
    },
    "language": {
        "_type": "CODE_PHRASE",
        "terminology_id": {
            "_type": "TERMINOLOGY_ID",
            "value": "ISO_639-1"
        },
        "code_string": "nl"
    },
    "territory": {
        "_type": "CODE_PHRASE",
        "terminology_id": {
            "_type": "TERMINOLOGY_ID",
            "value": "ISO_3166-1"
        },
        "code_string": "NL"
    },
...
    },
    "content": [
        {
            "_type": "EVALUATION",
            "name": {
                "_type": "DV_TEXT",
                "value": "Alcohol consumption summary"
            },
            "archetype_details": {
                "archetype_id": {
                    "value": "openEHR-EHR-EVALUATION.alcohol_consumption_summary.v1"
                },
                "rm_version": "1.0.4"
            },
            "language": {
                "_type": "CODE_PHRASE",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                },
                "code_string": "nl"
            },
            "encoding": {
                "_type": "CODE_PHRASE",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "IANA_character-sets"
                },
                "code_string": "UTF-8"
            },
            "subject": {
                "_type": "PARTY_SELF"
            },
            "data": {
                "_type": "ITEM_TREE",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Tree"
                },
                "items": [
                    {
                        "_type": "ELEMENT",
                        "name": {
                            "_type": "DV_TEXT",
                            "value": "Regular consumption commenced"  <-------- Variable name is in English instead of Dutch!
                        },
                        "value": {
                            "_type": "DV_DATE",
                            "value": "2011-12-01"
                        },
                        "archetype_node_id": "at0015"
                    },
                    {
                    ...
```

**Comment by stefanspiska** [comment]
What do you mean with Generated a composition using the REST transform API?.

I'm a complete loss what you are doing here.

**Comment by stefanspiska** [comment]
But that the generated classes uses the default language specified during the export of the OPT.

**Comment by hkabbech** [comment]
Is there a way to translate the composition / choose the language before generating compositions?
Or, as you mentioned, the only way would be to define which language is the primary language while downloading the OPT file?

**Comment by stefanspiska** [comment]
There is no feature in ehrbase or the sdk to automatically translate valueset between languages.

**Comment by hkabbech** [comment]
Thank you! I could indeed get the java classes in Dutch by downloading the OPT file with primary language as Dutch. That should do the trick.
