### ISSUE TITLE
Enum not generated because name collision (?)

### ISSUE THREAD

**Issue by ppazos** [ehrbase/openEHR_SDK#84]
## Steps to reproduce ## 

For the pregnancy status OPT https://ckm.highmed.org/ckm/templates/1246.169.1095

The SDK generator generated one class "StatusDefiningcode" that is one of two expected to be generated:

  - Node at0004 from the COMPOSITION is called "Status" and the correspondent Enum class is not generated (it's a coded text with 4 possible values at0010 to at0013).

  - Node at0011 from the OBSERVATION is called "Status" and the correspondent Enum is created with 3 possible values (at0012 to at0014) > https://github.com/ehrbase/fhir-bridge/blob/feature/50_mapping_pregnancy_status/src/main/java/org/ehrbase/fhirbridge/opt/schwangerschaftsstatuscomposition/definition/StatusDefiningcode.java

## Actual result ##

One class is missing.

And the field generated for the COMPOSITION actually points to the class generated for the OBSERVATION, which doesn't contain the right values. > https://github.com/ehrbase/fhir-bridge/blob/feature/50_mapping_pregnancy_status/src/main/java/org/ehrbase/fhirbridge/opt/schwangerschaftsstatuscomposition/SchwangerschaftsstatusComposition.java#L18

## Expected result ##

To have 2 classes generated and the COMPOSITION field "statusDefiningCode" to point to the right class > https://github.com/ehrbase/fhir-bridge/blob/feature/50_mapping_pregnancy_status/src/main/java/org/ehrbase/fhirbridge/opt/schwangerschaftsstatuscomposition/SchwangerschaftsstatusComposition.java#L44

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by jakesmolka** [comment]
Maybe linked to or same root problem like in https://github.com/ehrbase/project_management/issues/374
