### ISSUE TITLE
Issues with Flattener/Unflattener

### ISSUE THREAD

**Issue by chevalleyc** [ehrbase/openEHR_SDK#85]
## Steps to reproduce ## 

Flatten and unflatten composition using the attached template failed as follows (also attached the corresponding canonical json for use with Postman). Corresponding snippet is as follows:

```
        Composition composition = new CanonicalJson().unmarshal(IOUtils.toString(CompositionTestDataCanonicalJson.VIROLOGY_FINDING_WITH_SPECIMEN.getStream(), StandardCharsets.UTF_8), Composition.class);

        assertThat(composition.itemsAtPath("/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]")).isNotNull();

        Flattener flattener = new Flattener();

        VirologischerBefundComposition virologischerBefundComposition = flattener.flatten(composition, VirologischerBefundComposition.class);
        assertThat(virologischerBefundComposition.getBefund()).isNotNull();

        //with the test data
        virologischerBefundComposition = TestData.buildTestVirologischerBefundComposition();
        assertThat(virologischerBefundComposition.getBefund()).isNotNull();

        UUID ehr = openEhrClient.ehrEndpoint().createEhr();
        openEhrClient.compositionEndpoint(ehr).mergeCompositionEntity(virologischerBefundComposition);
```

1. Statement ` assertThat(virologischerBefundComposition.getBefund()).isNotNull();` fails

2. Statement `        openEhrClient.compositionEndpoint(ehr).mergeCompositionEntity(virologischerBefundComposition);
` raises a ClassCastException in Unflattener.java line 97:
```
           List valueList = (List) value;
            if (CollectionUtils.isNotEmpty((List) child)) {
                List childList = new ArrayList();
 ```
The test data snippet to construct the composition is attached below (the .txt should be removed...)

`TestData.buildTestVirologischerBefundComposition()`
[scratch_5.java.txt](https://github.com/ehrbase/openEHR_SDK/files/5280360/scratch_5.java.txt)

Canonical JSON

[virology_finding_with_specimen.json.txt](https://github.com/ehrbase/openEHR_SDK/files/5280381/virology_finding_with_specimen.json.txt)

Template
[Virologischer Befund.opt.txt](https://github.com/ehrbase/openEHR_SDK/files/5280386/Virologischer.Befund.opt.txt)

## Expected result ##

1. should be not null
2. no exception raised

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by stefanspiska** [comment]
In the template the name  of openEHR-EHR-OBSERVATION.laboratory_test_result is renamed from "Laborergebnis" to "Befund" however  virology_finding_with_specimen.json.txt the name of  openEHR-EHR-OBSERVATION.laboratory_test is "Laborergebnis". If I change it to "Befund" the first assert works.

The second assert was a bug in  handling of paths with names.

see

fixed in https://github.com/ehrbase/openEHR_SDK/pull/87
