### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by talex1** [ehrbase/openEHR_SDK#95]
I'm trying to build the project and get an error.
My mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_265, vendor: Private Build
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: pl_PL, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-117-generic", arch: "amd64", family: "unix"

## Steps to reproduce ## 

mvn clean install

## Actual result ##
 [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ opt-1.4 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 488 source files to /home/alex/praca/ALMAG/Bonasoft/openehr/openEHR_SDK-develop/opt-1.4/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] root ............................................... SUCCESS [  1.511 s]
[INFO] opt-1.4 ............................................ FAILURE [  8.186 s]
[INFO] test-data .......................................... SKIPPED
[INFO] web-template ....................................... SKIPPED
[INFO] serialisation ...................................... SKIPPED
[INFO] terminology ........................................ SKIPPED
[INFO] response-dto ....................................... SKIPPED
[INFO] validation ......................................... SKIPPED
[INFO] client ............................................. SKIPPED
[INFO] generator .......................................... SKIPPED
[INFO] code-coverage ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.984 s
[INFO] Finished at: 2020-10-03T12:46:50+02:00
[INFO] Final Memory: 22M/570M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project opt-1.4: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]

**Comment by birgerhaarbrandt** [comment]
It looks like you are using Java 8. Can you please try with 11(preferably openjdk) ?

**Comment by talex1** [comment]
With Java 11 is ok. Thanks :)
